find_path(LIBKINECTSDK_INCLUDE_DIR Kinect.h
		HINTS $ENV{KINECTSDK20_DIR}/inc)

find_library(LIB_KINECT_LIBRARY NAMES Kinect20.lib
		HINTS $ENV{KINECTSDK20_DIR}/lib/x64)
		
find_library(LIB_KINECT_FUSION_LIBRARY NAMES Kinect20.Fusion.lib
		HINTS $ENV{KINECTSDK20_DIR}/lib/x64)

set(LIBKINECTSDK_INCLUDE_DIRS ${LIBKINECTSDK_INCLUDE_DIR} )
set(LIBKINECTSDK_ALL_LIBRARIES ${LIB_KINECT_LIBRARY} ${LIB_KINECT_FUSION_LIBRARY})

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set LIBXML2_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(LIBKINECTSDK  DEFAULT_MSG
		LIBKINECTSDK_INCLUDE_DIRS LIBKINECTSDK_ALL_LIBRARIES)

mark_as_advanced(LIBKINECTSDK_INCLUDE_DIR LIB_KINECT_LIBRARY LIB_KINECT_FUSION_LIBRARY)
